name: release blasehttp windows gui

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  windows-gui-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Set up fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: build windows
        run: fyne-cross windows -app-id cn.chaitin.blazehttp -arch="amd64,arm64" ./gui

      - name: Normalise version tag
        id: normalise_version
        shell: bash
        run: |
          if [ "${{ github.event.release.tag_name }}" == "" ]; then
            version=$(echo ${{ github.event.inputs.tag }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            version=$(echo ${{ github.event.release.tag_name }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          fi
          mv ./fyne-cross/dist/windows-amd64/blazehttp.exe.zip ./fyne-cross/dist/windows-amd64/blazehttp_$version_windows_amd64_gui.zip
          mv ./fyne-cross/dist/windows-arm64/blazehttp.exe.zip ./fyne-cross/dist/windows-arm64/blazehttp_$version_windows_arm64_gui.zip

      - name: release gui
        uses: softprops/action-gh-release@v1
        with:
          if: startsWith(github.ref, 'refs/tags/')
          files: |
            ./fyne-cross/dist/windows-amd64/blazehttp_${{ steps.normalise_version.outputs.version }}_windows_amd64_gui.zip
            ./fyne-cross/dist/windows-arm64/blazehttp_${{ steps.normalise_version.outputs.version }}_windows_arm64_gui.zip
          token: ${{ secrets.GITHUB_TOKEN }}
