name: release blasehttp windows gui

permissions:
  contents: write

on:
  push:

jobs:
  windows-gui-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: build windows
        run: fyne-cross windows -app-id cn.chaitin.blazehttp -arch="*" ./gui
