name: release blasehttp macos gui

permissions:
  contents: write

on:
  push:

jobs:
  macos-gui-releaser:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Set up Docker
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      
      - name: Set up fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: build macos
        run: fyne-cross darwin -app-id cn.chaitin.blazehttp -arch="*" ./gui
